# Generated by Django 2.2.17 on 2021-03-23 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memebasket',
            name='meme_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memebasket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='memebasket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
