# Generated by Django 2.2.17 on 2021-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memecommerce', '0004_auto_20210324_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, upload_to='meme_photo'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
