# Generated by Django 2.2.17 on 2021-03-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memecommerce', '0007_auto_20210331_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, upload_to='memes/'),
        ),
    ]
