# Generated by Django 2.2.17 on 2021-04-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memecommerce', '0008_auto_20210331_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memeorder',
            name='memes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='memes',
        ),
        migrations.AddField(
            model_name='meme',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memeorder',
            name='ordered_meme',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='memecommerce.Meme'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='listed_memes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memecommerce.Meme'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='purchased_memes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memecommerce.MemeOrder'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='MemeBasket',
        ),
    ]
