# Generated by Django 2.2.17 on 2021-04-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memecommerce', '0009_auto_20210401_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='listed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MemeListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_listed', models.BooleanField(default=False)),
                ('listed_meme', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='memecommerce.Meme')),
            ],
        ),
    ]
