# Generated by Django 2.2.17 on 2021-04-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memecommerce', '0011_auto_20210402_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='purchased_memes',
            field=models.ManyToManyField(blank=True, to='memecommerce.Meme'),
        ),
    ]
