# Generated by Django 2.2.17 on 2021-04-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memecommerce', '0012_auto_20210403_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
