# Generated by Django 2.2.17 on 2021-04-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memecommerce', '0013_meme_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memecommerce.UserProfile'),
        ),
    ]
