# Generated by Django 2.2.17 on 2021-04-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memecommerce', '0016_meme_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='created',
            field=models.IntegerField(null=True),
        ),
    ]
